### ISSUE TITLE
azure key vault: base64 decode value fetched from upstream

### ISSUE THREAD

**Issue by jack1902** [helmfile/vals#145]
I'm using skaffold to do a deployment which is using the `helm-secrets` plugin to enable using secrets not stored within a git repo. The backend in use by `helm-secrets` is `vals` such that i can pull secrets from a central place such as Azure Key Vault.

The issue i am facing is that the values i have put into azure key vault are "certificates" which are base64'd by Azure Key Vault. This means that when i use helm-secrets which uses vals to get the value, it is already `base64` encoded.

This is problematic as i already pass values to my charts via other means which are NOT already base64 encoded. It feels wrong for me to go from the below which is passed into the chart via helm `--set-files` usually. (within a secret file):

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-certs
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  client.crt.pem: {{ required "Please set app.pem" .Values.app.pem | b64enc | quote }}
```

Because i already have this interface at use, ideally i would prefer that i could instrement `vals` in such a way to "base64-decode` the value returned from the azure key vault lookup else i end up having the value passed through to helm have `b64enc` applied to a value which is already base64 encoded which results in the value being consumed by my application not working (it expected the cert, not a base64 encoded cert).

Is there a way around this such that the value returned by vals on the lookup to Azure Key Vault is the base64 decoded value and not the base64 encoded value which is stored within Azure Key Vault (because it is a certificate this is how AKS stores them).
