### ISSUE TITLE
Using SOPS and AWS Secrets Manager at the same time causes SOPS to not decrypt

### ISSUE THREAD

**Issue by riain0** [helmfile/vals#148]
**Context**
Essentially, we use CDK to create databases and from this we get a reference to the secret created in AWS Secrets Manager which we then pass into the `values.yaml` and the value looks something like `cdkdbpass: ref+awssecrets://AuroraPostgresClusterapp-abcdef123`.

On the sops side of things we have a `secrets.yaml` then which contains something like:

```yaml
someSecret: ENC[...]
sops:
    kms:
        - arn: arn:aws:kms:blah
          created_at: "2019-02-11T09:32:05Z"
          enc: ...
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-25T07:16:04Z"
    mac: ENC[...]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
```
and then we reference `someSecret` in a Kubernetes opaque secret using `{{ .Values.someSecret | b64enc }}`

Our workflow then is to run helm secrets like this:

`helm secrets --backend vals template . -f envs/dev/values.yaml -f envs/dev/secrets.yaml`

What happens when we do this is that the SOPS secret doesn't get decrypted properly, it seems to copy the value from the `secrets.yaml` directly (the `ENC[...]` value) and then encodes it with base64.

To work around this, we needed to create a property like `secretRef: ref+sops://envs/dev/secrets.yaml#/monolithDb/pass` we then reference it in a Secret like:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Chart.Name }}
data:
  SECRET: {{ .Values.secretRef | b64enc | quote }}
```

Is this intended behaviour? I think if it is, at least an error should be thrown rather than copying the raw encrypted string into the K8s secret.
