### ISSUE TITLE
yaml block scalars

### ISSUE THREAD

**Issue by termit-uanic** [helmfile/vals#153]
I deploy kibana from the repository [https://github.com/elastic/helm-charts](https://github.com/elastic/helm-charts)

My values.yaml has the following lines

```
# Allows you to add any config files in /usr/share/kibana/config/
# such as kibana.yml
kibanaConfig:
  kibana.yml: |
    xpack.encryptedSavedObjects.encryptionKey: 71b27fd486e05***********
    xpack.reporting.encryptionKey: 8546a1e036a*********** 
    xpack.security.encryptionKey: 2e648b8f246e***********
    server.publicBaseUrl: https://***********.com
    elasticsearch.username: "***********"
    elasticsearch.password: "ref+awsssm://staging/elastic-tt-credentials?mode=singleparam"
```

I get the data from SSM. Only vals breaks this block.

When running
```
cat values.yaml | vals eval -f -
```
outputs
```
kibanaConfig:
  kibana.yml: "xpack.encryptedSavedObjects.encryptionKey: 71b27fd486e05***********\nxpack.reporting.encryptionKey: 8546a1e036a***********  \nxpack.security.encryptionKey: 2e648b8f246e***********\nserver.publicBaseUrl: https://***********.com\nelasticsearch.username: \""***********"\"\nelasticsearch.password: \"zKM1tg***********\"\n"
```

Deploy as follows
```
helm secrets --evaluate-templates upgrade --install -n testsecret kibana-tt-staging helm-charts/kibana/ --set imageTag=7.17.9 -f staging/values.yaml
```
When deploy via helm, the kibana.yml file in the pod does not contain this data

**Expectation:** 
vals should save yaml blocks according to the documentation [https://yaml-multiline.info/](https://yaml-multiline.info/) or [https://yaml.org/spec/1.2.2/#81-block-scalar-styles](https://yaml.org/spec/1.2.2/#81-block-scalar-styles)
