### ISSUE TITLE
Bug: Multi resource yaml does not work since v0.26.1

### ISSUE THREAD

**Issue by alexintech** [helmfile/vals#155]
Hi!

It seems that version 0.26.1 had introduced a bug processing multi resource yaml files.

**How to reproduce**
Create a file such as `example.yaml`:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
---
apiVersion: v1
kind: Secret
data:
  username: ref+sops://secrets.enc.yaml/#username
```

Running `vals eval -f manifests/example.yaml` outputs:
```
sops: successfully retrieved key=secrets.enc.yaml
null
```

On version `0.26.0` it works correctly:
```
sops: successfully retrieved key=secrets.enc.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
---
apiVersion: v1
data:
  username: ****
kind: Secret
```
