### ISSUE TITLE
vals eval produces invalid template on comments only sections

### ISSUE THREAD

**Issue by alstephenclaypool** [helmfile/vals#165]
Example helm chart
```yaml
apiVersion: v2
name: test
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: 1.0.0
dependencies:
- name: prometheus-operator
  version: 8.3.0
  repository: https://charts.helm.sh/stable
```

If this is used to produce a template running simply `helm template --release-name vals-test --namespace vals-test  .` the resulting template will look something like

```yaml
---
# Source: test/charts/prometheus-operator/charts/grafana/templates/podsecuritypolicy.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: vals-test-grafana
  namespace: vals-test
  labels:
    app: grafana
    chart: grafana-4.0.2
    heritage: Helm
    release: vals-test
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
# ... much later on
---
# Source: test/charts/prometheus-operator/templates/grafana/dashboards/nodes.yaml
# Generated from 'nodes' from https://raw.githubusercontent.com/coreos/kube-prometheus/release-0.1/manifests/grafana-dashboardDefinitions.yaml
# Do not change in-place! In order to change this file first read following link:
# https://github.com/helm/charts/tree/master/stable/prometheus-operator/hack
---
# Source: test/charts/prometheus-operator/templates/grafana/dashboards/persistentvolumesusage.yaml
# Generated from 'persistentvolumesusage' from https://raw.githubusercontent.com/coreos/kube-prometheus/release-0.1/manifests/grafana-dashboardDefinitions.yaml
# Do not change in-place! In order to change this file first read following link:
# https://github.com/helm/charts/tree/master/stable/prometheus-operator/hack
```

If the fully rendered template is passed to `vals eval` then the comment only sections get replaced with

```yaml
---
{}
---
{}
```

This evaluated template when applied to kubernetes using `kubectl apply -f vals-evaluated-template.yaml` throws a validation error which does not happen in the original non-evaluated template where there are no empty objects.

```
error validating "vals-evaluated-template.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
```
