### ISSUE TITLE
"Custom command" plugin to retrieve passwords from any backend that have cli interface

### ISSUE THREAD

**Issue by MurzNN** [helmfile/vals#193]
Will be good to implement a "custom command" plugin, that will run a specific command and parse the output to retrieve the value.

For example, we have no integration for Bitwarden secrets storage backend. But Bitwarden provides a good [cli interface](https://bitwarden.com/help/cli/) that can be used to retrieve the values.

For example, we can introduce the configuration like this:
```yaml
name: bitwarden
dataFormat: {id}/{fieldname}
commandTemplate: bw get {fieldname} {id}
outputType: json # plaintext|json|yaml
outputValue: data.{fieldname} # JSON path, or YAML path, or Regexp
```
And then, we can refer to this provider like this:
```yaml
password: ref+bitwarden://35ab2e78-7d47-49e5-b72f-d8c7cbc32531/password
```

And the same approach can cover any other secrets storage that provides command line interface!

What do you think about this idea?
