### ISSUE TITLE
Feature: Support complex values

### ISSUE THREAD

**Issue by jkroepke** [helmfile/vals#205]
### Current Behavior

When I have the following template:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
stringData: ref+awsssm://test
```
With a value in Parameter Store in YAML format:

```yaml
value1: secret
value2: secret
```

I get the following rendered secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
stringData: |-
  value1: secret
  value2: secret
```

I would like to give vals an hint that the value should be not handle as string, instead it just be insert as object into the existing yaml structure.

for example:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
stringData:
  value1: secret
  value2: secret
```
