### ISSUE TITLE
fetch values from terraform state fails after helmfile 0.156.0

### ISSUE THREAD

**Issue by Sajfer** [helmfile/vals#230]
### Operating system

ubuntu 22.04.3

### Helmfile Version

helmfile version 0.157.0

### Helm Version

version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

### Bug description

Trying to fetch a terraform state value ends up returning`null"address-2"].address` instead of the expected value.

I have tested with helmfile 0.156.0 and it works, but every version after that gives back the null value.

The string we are trying to fetch is `"ref+tfstategs://helmfile_example_tfstate/default.tfstate/google_compute_address.internal-ips[\"address-2\"].address"`

### Example helmfile.yaml
```
bases:
  - common/environments.yaml

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

templates:
  bitnami: &bitnami
    chart: bitnami/{{`{{ .Release.Name }}`}}
    namespace: "{{`{{ .Release.Name }}`}}"
    missingFileHandler: Warn
    values:
    - config/{{`{{ .Release.Name }}`}}/values.yaml
    - config/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl

releases:
  - name: haproxy
    version: 0.14.3
    <<: *bitnami
```

### Error message you've seen (if any)

No error message shown

### Steps to reproduce

https://github.com/Sajfer/helmfile_bug_example

### Working Helmfile Version

helmfile version 0.156.0
