### ISSUE TITLE
Error expanding GCP secrets

### ISSUE THREAD

**Issue by dovvla** [helmfile/vals#291]
Hi,

I have an issue where when I try to reference secret from gcpsecrets additional fields get concatenated to the URI.  To be more precise, here is what happened:

```yaml
#values.yaml
  defaultDbPassword: ref+gcpsecrets://<project_name>/<secret_name>
  database:
    default:
      writeHostUrl: "127.0.0.2"
      readOnlyHostUrl: "127.0.0.3"
      database: <db_name>
```
Upon running `helm secrets --evaluate-templates upgrade --install` the following error is thrown:
```
expand gcpsecrets://<project_name>/<secret_name>@tcp(127.0.0.2)/<db_name>: failed to get secret: rpc error: code = InvalidArgument desc = The provided Secret ID [projects/<project_name>/secrets/t<secret_name>@tcp(127.0.0.2)/<db_name>/versions/latest] does not match the expected format [projects/*/secrets/*/versions/*]'
```
