### ISSUE TITLE
Issue with Using vals for Credentials in Helmfile

### ISSUE THREAD

**Issue by sule26** [helmfile/vals#511]
I'm trying to access a Helm chart from a private repository within my company, and I've followed the Helmfile documentation for passing credentials. However, I encountered an issue where I could only retrieve the Helm chart when the username and password were specified as plain text.

Since vals is a project associated with Helmfile, it seems logical to integrate vals directly within Helmfile for handling sensitive information. Here's how I've attempted to configure it:

```yaml
repositories:
  - name: bdc-helm
    url: https://private-chart
    username: ref+awssecrets://test?region=us-east-1#/username
    password: ref+awssecrets://test?region=us-east-1#/password
    passCredentials: true
...
```

In this configuration, I'm using ref+awssecrets to reference credentials from AWS Secrets Manager. However, it appears that this approach does not work as expected for authenticating with the private repository.

Is there a recommended way to use vals with Helmfile for securely passing credentials, or am I missing something in the configuration? Any guidance or suggestions would be appreciated.
