### ISSUE TITLE
[Bug] ref+sops:// not working correctly with sub-helmfiles and same sops value file names for sub charts

### ISSUE THREAD

**Issue by Marcel1802** [helmfile/vals#630]
## The problem:

I have a helmfile that calls sub-helmfiles. 
In every of those sub-helmfiles, I get encrypted values via ref+sops://. 
The filename of my encrypted values file is always the same for every sub-helmfile.

When only calling / executing each sub-helmfile, everything is working well.

When calling my main helmfile which calls all sub helmfiles, the values for the first sub-helmfile are fetched as expected. All other helmfiles get empty values. Helmfile does not say that it cannot find the file [!]. The values are just empty.

The logs also say that sops successfully get my values.sops.yaml only once, not one time per sub helmfile.

## How to reproduce

Create a file structure like this:

```
module_backup/
    helmfile.yaml
    values.sops.yaml
module_cluster/
    helmfile.yaml
    values.sops.yaml
module_monitoring/
    helmfile.yaml
    values.sops.yaml
helmfile.yaml
```

The main helmfile at root level looks like this:
```yaml
helmDefaults:
  timeout: 300
  [...]

helmfiles:
  - path: ./module_*/helmfile.yaml

```

And the `module_monitoring/helmfile.yaml` looks like

```yaml
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
[...]

releases:
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    # renovate: datasource=helm depName=grafana/grafana
    version: 8.8.5
    values:
      - ./v-grafana.yaml
      - grafana.ini:
          auth.generic_oauth:
            client_id: "ref+sops://values.sops.yaml#/grafana/auth/clientid"
            client_secret: "ref+sops://values.sops.yaml#/grafana/auth/secret"
    labels:
      app: grafana
[...]

```

And in the values of a helm release in the `module_backup/helmfile.yaml` there is something like
```yaml
[...]
values:
- s3bucket:
    accessId: "ref+sops://values.sops.yaml#/s3bucket/accessId"
    secretKey: "ref+sops://values.sops.yaml#/s3bucket/secretKey"
[...]
```

**In both sub-helmfiles, the same file name is referenced.**
Since the starting point of the relative path to the `values.sops.yaml` is the sub-helmfile, they should be considered two different files when they are called from the main helmfile in the root directory.

## Expected behaviour

All values.sops.yaml files are treated as different files, not ignoring every file after the first one since a file with that name was already loaded.

## My workaround

My workaround is calling the file differently for each sub-helmchart, e.g. values-monitoring.sops.yaml, values-backup.sops.yaml etc.
