### ISSUE TITLE
vals modifies plain date strings in YAML, adding time and timezone information

### ISSUE THREAD

**Issue by Skaronator** [helmfile/vals#665]
I'm using `vals` with ArgoCD to process Helm value files, including post `helm template` processing for edge case handling. I've encountered an issue where `vals` unexpectedly modifies plain date strings within YAML files.

**Steps to Reproduce:**

1.  Create a YAML file (e.g., `demo.yaml`) with a date string in the format `YYYY-MM-DD`. For example:

    ```yaml
    schemaConfig:
      configs:
        - from: 2025-01-01
          object_store: s3
          store: tsdb
          schema: v13
          index:
            prefix: index-
            period: 24h
    ```

2.  Run `vals eval -f demo.yaml`.

**Expected Behavior:**

`vals` should leave the date string `2025-01-01` unchanged. I expect `vals` to only modify strings that explicitly indicate a `ref+<type>` reference.

**Actual Behavior:**

`vals` modifies the date string to `2025-01-01T00:00:00Z`.

```bash
$ vals eval -f demo.yaml
schemaConfig:
  configs:
    - from: 2025-01-01T00:00:00Z
      index:
        period: 24h
        prefix: index-
      object_store: s3
      schema: v13
      store: tsdb
```

**Environment:**

vals version: 0.39.4
Operating system: WSL Debian and within ArgoCD Container

**Additional Information:**

* While quoting the date string (e.g., "2025-01-01") avoids this modification, it's not a viable workaround because helm template removes unnecessary quotes.
